// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okisvoalmfkohpuymzmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9raXN2b2FsbWZrb2hwdXltem1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1MDE2NjQsImV4cCI6MjA4NzA3NzY2NH0.WKVj9Os4Zei6lNhVcSQkmf5EIZIoJa2M0boj-XBfPJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});